/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import hibernatedao.BbsuserDAO;
import hibernatedao.Bbsuser;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Transaction;

import com.yourcompany.struts.form.EditForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-06-2012
 * 
 * XDoclet definition:
 * @struts.action path="/edit" name="editForm" input="/form/edit.jsp" scope="request" validate="true"
 */
public class EditAction extends Action {
	/*
	 * Generated Methods
	 */
	private BbsuserDAO dao;
	
	public EditAction(){
		setDao(new BbsuserDAO());
	}
	
	public static String isToGB(String src){
		String strRet = null;
		try{
			strRet = new String(src.getBytes("UTF-8"),"GBK");
		}
		catch(Exception e){
			e.printStackTrace();
		}
		return strRet;
	}
	
	public BbsuserDAO getDao() {
		return dao;
	}


	public void setDao(BbsuserDAO dao) {
		this.dao = dao;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EditForm editForm = (EditForm) form;// TODO Auto-generated method stub
		try{
			//Bbsuser user  = new Bbsuser();
			Bbsuser user = (Bbsuser) request.getSession().getAttribute("s_user");
			System.out.println("ÐÞ¸Ä£º");
			user.setUsername(editForm.getUsername());
			user.setPassword(editForm.getPassword());
			user.setTelephone(editForm.getTelephone());
			user.setAddress(editForm.getAddress());
			user.setStudentid(editForm.getStudentid());
			user.setCollege(editForm.getCollege());
			/*if(user == null){
				System.out.println("new :");
				user = new Bbsuser();
			}*/
			
			//user.setUsername(registerForm.getUsername());
			//user.setPassword(registerForm.getPassword());
			user.setAge(21);
			
			//BbsuserDAO dao = new BbsuserDAO();
			BbsuserDAO dao = getDao();
			Transaction tran = dao.getSession().beginTransaction();
			
			dao.attachDirty(user);
			tran.commit();
		}
		catch(Exception e){
			e.printStackTrace();
		}
		return mapping.findForward("edit_success");
	}
}