/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-27-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="go_register" path="/form/register.jsp"
 * @struts.action-forward name="go_login" path="/form/userLogin.jsp"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String n_id = request.getParameter("myid");
		System.out.println(n_id);
		if(n_id.equals("1")){
			try{
				request.getSession().removeAttribute("s_user");
			}
			catch(Exception e){
				e.printStackTrace();
			}
			return mapping.findForward("go_register");
		}
		return mapping.findForward("go_login");
	}
}