/*
 * Generated by MyEclipse Struts

 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import hibernatedao.Bbsuser;


import hibernatedao.BbsuserDAO;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Transaction;

import com.yourcompany.struts.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-25-2012
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="registerForm" input="/form/register.jsp" scope="request" validate="true"
 * @struts.action-forward name="failed" path="/failed.jsp"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class RegisterAction extends Action {
	private BbsuserDAO dao;
	public RegisterAction(){
		setDao(new BbsuserDAO());
	}
	public static String isToGB(String src){
		String strRet = null;
		try{
			strRet = new String(src.getBytes("UTF-8"),"GBK");
		}
		catch(Exception e){
			e.printStackTrace();
		}
		return strRet;
	}
	public BbsuserDAO getDao() {
		return dao;
	}
	public void setDao(BbsuserDAO dao) {
		this.dao = dao;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated method stub
		try{
			
			Bbsuser user = new Bbsuser();
			user.setUsername(registerForm.getUsername());
			user.setPassword(registerForm.getPassword());
			user.setTelephone(registerForm.getTelephone());
			user.setAddress(registerForm.getAddress());
			user.setStudentid(registerForm.getStudentid());
			user.setCollege(registerForm.getCollege());
			user.setAge(21);
			BbsuserDAO dao = getDao();
			Transaction tran = dao.getSession().beginTransaction();
			dao.attachDirty(user);
			tran.commit();
		}
		catch(Exception e){
			e.printStackTrace();
		}
		return mapping.findForward("success");
	}

}