/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import hibernatedao.Bbsuser;
import hibernatedao.BbsuserDAO;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.SearchForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-05-2012
 * 
 * XDoclet definition:
 * @struts.action path="/search" name="searchForm" input="/form/search.jsp" scope="request" validate="true"
 */
public class SearchAction extends Action {
	/*
	 * Generated Methods
	 */
	private BbsuserDAO dao;
	public SearchAction(){
		setDao(new BbsuserDAO());
	}
	
	public BbsuserDAO getDao() {
		return dao;
	}

	public void setDao(BbsuserDAO dao) {
		this.dao = dao;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchForm searchForm = (SearchForm) form;// TODO Auto-generated method stub
		BbsuserDAO dao = getDao();
		Bbsuser user = dao.CheckLogin(searchForm.getUsername(), searchForm.getPassword());
		
		if(user != null){
			request.setAttribute("Login_UserName", searchForm.getUsername());
			
			//if(searchForm.getUsername().equals("ldg")){
				//userLoginForm.setUserList(dao.findAll());
			if(searchForm.getSearch_username().equals("")){
				request.getSession().setAttribute("s_userlist", dao.findAll());
			}
			else{
				request.getSession().setAttribute("s_userlist", dao.findByUsername(searchForm.getSearch_username()));
			}
			System.out.println("find all");
			return mapping.findForward("success");
			//}
			
			//return mapping.findForward("success");
		}
		/*java.util.List results = dao.findByUsername(userLoginForm.getUsername());
		
		if(results != null && results.size()>0){
			Bbsuser user = (Bbsuser)results.get(0);
			if(user.getPassword().equals(userLoginForm.getPassword())){
				System.out.println(userLoginForm.getUsername());
				request.setAttribute("Login_UserName", userLoginForm.getUsername());
				return mapping.findForward("success");
			}
		}*///2012/11/26
		/*if (userLoginForm.getUsername().equals("yy")){
			request.setAttribute("Login_UserName", userLoginForm.getUsername());
			return mapping.findForward("success");
		}*/
		System.out.println("login failed");
		return mapping.findForward("failed");
	}
}