/*
 * Generated by MyEclipse Struts

 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import hibernatedao.Bbsuser;
import hibernatedao.BbsuserDAO;

import javax.servlet.http.HttpServletRequest;

import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.UserLoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-26-2012
 * 
 * XDoclet definition:
 * @struts.action path="/userLogin" name="userLoginForm" input="/form/userLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="failed" path="/UserLogin.jsp"
 * @struts.action-forward name="success" path="/UserLoginSuccess.jsp"
 */
public class UserLoginAction extends Action {
	
	private BbsuserDAO dao;
	public UserLoginAction(){
		setDao(new BbsuserDAO());
	}
	
	public BbsuserDAO getDao() {
		return dao;
	}

	public void setDao(BbsuserDAO dao) {
		this.dao = dao;
	}
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserLoginForm userLoginForm = (UserLoginForm) form;// TODO Auto-generated method stub
		BbsuserDAO dao = getDao();
		Bbsuser user = dao.CheckLogin(userLoginForm.getUsername(), userLoginForm.getPassword());
		
		if(user != null){
			request.setAttribute("Login_UserName", userLoginForm.getUsername());
			
			if(userLoginForm.getUsername().equals("Administrator")){
				
				request.getSession().setAttribute("s_userlist", dao.findAll());
				System.out.println("find all");
				return mapping.findForward("admin_success");
			}
			request.getSession().setAttribute("s_userlist", dao.findAll());
			return mapping.findForward("success");
		}
		
		System.out.println("login failed");
		return mapping.findForward("failed");
	}
}